language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

env:
  - QMAKE_OPTIONS="CONFIG+=debug CONFIG+=qml_debug"
  - QMAKE_OPTIONS="CONFIG+=release"

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  - sudo apt-get -y install qt58serialbus
  - git clone git://github.com/stephane/libmodbus.git
  - cd libmodbus
  - git checkout f9358460ee1f62bcac716ad0444b3bbe7628b204
  - ./autogen.sh
  - ./configure
  - make && sudo make install
  - cd ..

script:
  - source /opt/qt58/bin/qt58-env.sh
  - mkdir build && cd build
  - /opt/qt58/bin/qmake ../All.pro $QMAKE_OPTIONS
  - make
