language: cpp
sudo: required
dist: xenial

branches:
  only:
  - 1
  - travis

git:
  submodules: false

compiler:
  - clang
  - gcc

env:
  - QBS_ENV="release"
  - QBS_ENV="debug"

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt596-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59-meta-minimal
  - sudo apt-get -y install qt59qbs
  - sudo apt-get -y install qt59serialbus
  - sudo apt-get -y install libssh-dev
  - git clone git://github.com/stephane/libmodbus.git
  - cd libmodbus
  - git checkout f9358460ee1f62bcac716ad0444b3bbe7628b204
  - ./autogen.sh
  - ./configure
  - make && sudo make install
  - cd ..
  - source /opt/qt59/bin/qt59-env.sh
  - qbs setup-toolchains --detect
  - qbs setup-qt /opt/qt59/bin/qmake qt59
  - qbs config profiles.qt59.baseProfile $CC

script:
  - qbs build -f CuteHMI.qbs -d build --command-echo-mode command-line profile:qt59 config:$QBS_ENV
